INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO,PAIS) VALUES ('PEREZ', '1', 'ROBERTO', '093939393','COSTA RICA' );
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO,PAIS) VALUES ('SANCHEZ', '2', 'RAUL', '093223333','COSTA RICA');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO,PAIS) VALUES ('SANCHEZ PAZMINO', '11', 'PATRICIO', '092222','PANAMA');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO,PAIS) VALUES ('SANCHEZ SALAZAR', '111', 'MAURICIO', '0933333','PANAMA');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO,PAIS) VALUES ('SANCHEZ SALAZAR', '1111', 'HORACIO', '0934555','PANAMA');

INSERT INTO CUENTA(ESTADO,NUMERO,TIPO,CLIENTE_ID,ESTADO) VALUES ('ACTIVA','10022334','CREDITO',true);
INSERT INTO CUENTA(ESTADO,NUMERO,TIPO,CLIENTE_ID,ESTADO ) VALUES ('ACTIVA','10022334','CREDITO',true);
INSERT INTO CUENTA(ESTADO,NUMERO,TIPO,CLIENTE_ID,ESTADO ) VALUES ('INACTIVA','10022334','CREDITO',false)